#!/bin/bash

docker run --rm -ti \
	-u `id -u`:`id -g` \
	-v $CRUN_PATH:$CRUN_PATH \
	-v $PWD:$PWD \
	--workdir=$PWD \
	-e VERSION=$VERSION \
	-e EXPOSE=$EXPOSE \
	-e GPU="$GPU" \
	-e GPU_RUNTIME="$GPU_RUNTIME" \
	-e NETWORK="$NETWORK" \
	-e CLEANNAME="$CLEANNAME" \
	-e GIT_DIR="$PWD" \
	-e USR=`id -un` \
	-e NOCACHE="$NOCACHE" \
	ruby ruby "$@"
