#!/bin/bash

TTY_FLAGS="-i"
[ -t 0 ] && [ -t 1 ] && TTY_FLAGS="-it"

docker run --rm $TTY_FLAGS \
	-u `id -u`:`id -g` \
	-v $CRUN_PATH:$CRUN_PATH \
	-v $PWD:$PWD \
	--workdir=$PWD \
	-e VERSION=$VERSION \
	-e EXPOSE=$EXPOSE \
	-e GPU="$GPU" \
	-e GPU_RUNTIME="$GPU_RUNTIME" \
	-e NETWORK="$NETWORK" \
	-e NAME="$NAME" \
	-e CLEANNAME="$CLEANNAME" \
	-e GIT_DIR="$PWD" \
	-e USR=`id -un` \
	-e NOCACHE="$NOCACHE" \
	-e NOUSERDEF="$NOUSERDEF" \
	ruby ruby "$@"
